### ISSUE TITLE
Invalid request leads to fatal error

### ISSUE THREAD

**Issue by nschilling** [academe/OmniPay-Payone#31]
I'm getting a fatal error when creating an invalid request on branch 3.0.0:

> Fatal error: Class 'Omnipay\Payone\Traits\InvalidRequestException' not found in ... academe/omnipay-payone/src/Traits/HasGatewayParams.php on line 85

I think there's an import missing in file /src/Traits/HasGatewayParams.php.
Adding `use Omnipay\Common\Exception\InvalidRequestException;` seems to fix the Issue.

**Comment by judgej** [comment]
Thanks - should be fixed. I'll do a debug release shortly.

**Comment by nschilling** [comment]
Thanks. Updated to 3.0.1 and the error is gone.
