### ISSUE TITLE
set personal data for clearingtypes other than creditcard

### ISSUE THREAD

**Issue by timo75** [academe/OmniPay-Payone#34]
I find it a bit strange that in ShopServer gateway for clearingtypes other than creditcard the only way to set personal data like fistName, lastName, billingCountry is by 'card' => ['firstName' => ... ]
Is there a reason  why this is so focused on card authorizations? Or am I overseeing something?

**Comment by judgej** [comment]
Omnipay has a long history, starting from when only credit cards needed to be supported, and long before PCI requirements stopped (discouraged) sites handling credit card details directly. It still retains a lot of that legacy structure, and that is what you are seeing.

Ultimately what I would like to see are separate classes for personal details, payment types, shipping methods and so on. We aren't there yet, so personal details go into the mis-named credit card object. You don't need to put credit card details into that object though, just use it for personal details.

Gateways that support other payment types will handle it their own way. Collecting together all of these methods from all the 100+ Omnipay gateways to standardise them is a massive job, but yeah, I think it needs to happen at some point. I hint at this here, and you can follow the chain https://github.com/academe/OmniPay-Payone/issues/7 turning a big ship like this around is not easy.

**Comment by timo75** [comment]
Hi Jason, Thanks for the quick response & explanation. Good to know.
