### ISSUE TITLE
Support for subscriptions/recurring payments

### ISSUE THREAD

**Issue by cthiele-mogic** [academe/OmniPay-Payone#36]
Hi, 

is the feature subscription plans/recurring payments supported or planned to be supported in future?  Feature exists in Payone API. 

Bye
Christian

**Comment by judgej** [comment]
There aren't any plans to extend this Omnipay driver beyond the basics of what Omnipay supports (essentially auth, pay, create token for repeat payments).

However, PRs are welcome if there are additional features you want to add.

**Comment by cthiele-mogic** [comment]
Are there any parts for recurring payments already integrated in the payone gateway for omnipay? I did not find anything.

**Comment by judgej** [comment]
It's been a while since I looked at this, so memory is rusty. You can do a "card check" and ask for the credit card to be stored. This give you a token for making payments. I'm not sure if that lets you take multiple future payments or not, so best check the docs.

Sorry it's not a definite answer.

**Comment by Axent96** [comment]
#42 
If some websource not allow for creditCard data for "card check" we can use recurring payment via alias/userId
https://docs.payone.com/display/public/PLATFORM/Special+remarks+-+Recurring+transactions+credit+card#expand-SampleInitialRequest

**Comment by Axent96** [comment]
@judgej Do you can merge please the pull request #42 for this issue?

**Comment by Axent96** [comment]
@judgej  Do you plan to solve the issue or merge PR #42 ?

**Comment by judgej** [comment]
In release 3.1.0
