### ISSUE TITLE
More than 10 items bug

### ISSUE THREAD

**Issue by adovbos** [academe/OmniPay-Payone#38]
https://github.com/academe/OmniPay-Payone/blob/7407f06df5956718fdfacf2f99e91d2b8df42728/src/Message/AbstractRequest.php#L228

If we send to payone request with more than 10 items, they sorted in SORT_REGULAR way, mean [1, 10, 11, 2] and we get Payone error "Hashwert nicht korrekt.". Should be sorted with flag SORT_NATURAL to make it work

**Comment by judgej** [comment]
In release 3.1.0
